version: '3.8'

services:
  app:
    image: mi-api
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mi-mysql
      DB_PORT: 3306
      DB_DATABASE: K_API
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8
    container_name: mi-mysql
    restart: always
    environment:
      MYSQL_DATABASE: K_API
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
